### ISSUE TITLE
On Platform.sh this requires server_variable configuration for Doctrine

### ISSUE THREAD

**Issue by janit** [ezsystems/ezcommerce#4]
Due to unknown reasons (to me), installation to Platform.sh / eZ Platform Cloud you need to define the `server_version` variable for Doctrine to `mariadb-10.2.12`. More information in this ticket: https://github.com/doctrine/DoctrineBundle/issues/673

Example configuration (in `app/config/config.yaml`):

```
doctrine:
    dbal:
        connections:
            default:
                driver: '%database_driver%'
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'
                charset: utf8mb4
                server_version: mariadb-10.2.12
```
